/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Karolis
 * Created: Feb 28, 2016
 */
CREATE TABLE PERSONALAS
(
	ID                  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VARDAS              VARCHAR(20),
        PAVARDE             VARCHAR(20),
        ASMENS_KODAS        CHAR(11) NOT NULL,
        OPT_LOCK_VERSION    INTEGER,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PERSONALAS_DALYKINISRAKTAS ON PERSONALAS
(
	ASMENS_KODAS
);



CREATE TABLE TROBELE
(
	ID                  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PAVADINIMAS         VARCHAR(20) NOT NULL,
        KAMBARIU_SKAICIUS   INTEGER DEFAULT 1,
        REZERVUOTAS         BOOLEAN DEFAULT FALSE,
        OPT_LOCK_VERSION    INTEGER,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX TROBELE_DALYKINISRAKTAS ON TROBELE
(
	PAVADINIMAS
);



CREATE TABLE PERSONALAS_TROBELE
(
	PERSONALAS_ID       INTEGER NOT NULL,
        TROBELE_ID          INTEGER NOT NULL,
	PRIMARY KEY (PERSONALAS_ID,TROBELE_ID),
        FOREIGN KEY (PERSONALAS_ID) REFERENCES PERSONALAS (ID),
        FOREIGN KEY (TROBELE_ID) REFERENCES TROBELE (ID)
);



CREATE TABLE PIRMUMO_GRUPE
(
	ID                  INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	PAVADINIMAS         VARCHAR(20) NOT NULL,
        PRIORITETAS         INTEGER,
        OPT_LOCK_VERSION    INTEGER,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PIRMUMO_GRUPE_DALYKINISRAKTAS ON PIRMUMO_GRUPE
(
	PAVADINIMAS
);



CREATE TABLE VARTOTOJAS
(
	ID                   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	VARDAS               VARCHAR(20),
	PAVARDE              VARCHAR(20),
	ASMENS_KODAS         INTEGER     NOT NULL,
	RANKAS               VARCHAR(20),
        PIRMUMO_GRUPE_ID     INTEGER,
        OPT_LOCK_VERSION    INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (PIRMUMO_GRUPE_ID) REFERENCES PIRMUMO_GRUPE (ID)
);
CREATE UNIQUE INDEX VARTOTOJAS_DALYKINISRAKTAS ON VARTOTOJAS
(
	ASMENS_KODAS
);